### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/home/seulab/seulab_ssd/dcc/VISAM-main/data/Dataset/mot/crowdhuman/Crowdhuman_val/273278,13cb1d00077bf3676.jpg'

### ISSUE THREAD

**Issue by dccdcc7** [BingfengYan/MOTSAM#6]
Traceback (most recent call last):
  File "main.py", line 396, in <module>
    main(args)
  File "main.py", line 355, in main
    train_stats = train_one_epoch_mot(
  File "/home/seulab/seulab_ssd/dcc/VISAM-main/exps/motrv2ch_uni5cost3ggoon/run46/engine.py", line 52, in train_one_epoch_mot
    for data_dict in metric_logger.log_every(data_loader, print_freq, header):
  File "/home/seulab/seulab_ssd/dcc/VISAM-main/exps/motrv2ch_uni5cost3ggoon/run46/util/misc.py", line 229, in log_every
    for obj in iterable:
  File "/home/seulab/miniconda3/envs/motrv2/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 630, in __next__
    data = self._next_data()
  File "/home/seulab/miniconda3/envs/motrv2/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 674, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/home/seulab/miniconda3/envs/motrv2/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/seulab/miniconda3/envs/motrv2/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/seulab/seulab_ssd/dcc/VISAM-main/exps/motrv2ch_uni5cost3ggoon/run46/datasets/dance.py", line 235, in __getitem__
    images, targets = self.load_crowd(idx - len(self.indices))
  File "/home/seulab/seulab_ssd/dcc/VISAM-main/exps/motrv2ch_uni5cost3ggoon/run46/datasets/dance.py", line 140, in load_crowd
    img = Image.open(img_path)
  File "/home/seulab/miniconda3/envs/motrv2/lib/python3.8/site-packages/PIL/Image.py", line 3247, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/home/seulab/seulab_ssd/dcc/VISAM-main/data/Dataset/mot/crowdhuman/Crowdhuman_val/273278,13cb1d00077bf3676.jpg'
请问这是哪里出现问题了

**Comment by fengxiuyaun** [comment]
这个是你没有crowdhuman这个数据集吧



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年2月26日(星期一) 下午5:02
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [BingfengYan/VISAM] FileNotFoundError: [Errno 2] No such file or directory: &#39;/home/seulab/seulab_ssd/dcc/VISAM-main/data/Dataset/mot/crowdhuman/Crowdhuman_val/273278,13cb1d00077bf3676.jpg&#39; (Issue #6)





 
Traceback (most recent call last):
 File "main.py", line 396, in 
 main(args)
 File "main.py", line 355, in main
 train_stats = train_one_epoch_mot(
 File "/home/seulab/seulab_ssd/dcc/VISAM-main/exps/motrv2ch_uni5cost3ggoon/run46/engine.py", line 52, in train_one_epoch_mot
 for data_dict in metric_logger.log_every(data_loader, print_freq, header):
 File "/home/seulab/seulab_ssd/dcc/VISAM-main/exps/motrv2ch_uni5cost3ggoon/run46/util/misc.py", line 229, in log_every
 for obj in iterable:
 File "/home/seulab/miniconda3/envs/motrv2/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 630, in next
 data = self._next_data()
 File "/home/seulab/miniconda3/envs/motrv2/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 674, in _next_data
 data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
 File "/home/seulab/miniconda3/envs/motrv2/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 51, in fetch
 data = [self.dataset[idx] for idx in possibly_batched_index]
 File "/home/seulab/miniconda3/envs/motrv2/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 51, in 
 data = [self.dataset[idx] for idx in possibly_batched_index]
 File "/home/seulab/seulab_ssd/dcc/VISAM-main/exps/motrv2ch_uni5cost3ggoon/run46/datasets/dance.py", line 235, in getitem
 images, targets = self.load_crowd(idx - len(self.indices))
 File "/home/seulab/seulab_ssd/dcc/VISAM-main/exps/motrv2ch_uni5cost3ggoon/run46/datasets/dance.py", line 140, in load_crowd
 img = Image.open(img_path)
 File "/home/seulab/miniconda3/envs/motrv2/lib/python3.8/site-packages/PIL/Image.py", line 3247, in open
 fp = builtins.open(filename, "rb")
 FileNotFoundError: [Errno 2] No such file or directory: '/home/seulab/seulab_ssd/dcc/VISAM-main/data/Dataset/mot/crowdhuman/Crowdhuman_val/273278,13cb1d00077bf3676.jpg'
 请问这是哪里出现问题了
